version: '2'
services:
  merch-it-api.db:
    image: postgres
  merch-it-api.web:
    build: .
    command: bundle exec rails s -p 3001 -b '0.0.0.0'
    volumes:
      - .:/merch-it
    ports:
      - "3001:3001"
    links:
      - merch-it-api.db:db
    depends_on:
      - merch-it-api.db
